### ISSUE TITLE
Firefox: uncaught exception: emscripten_get_num_gamepads() can only be called after having first called emscripten_sample_gamepad_data()

### ISSUE THREAD

**Issue by ufna** [ufna/UE-HTML5#28]
> uncaught exception: emscripten_get_num_gamepads() can only be called after having first called emscripten_sample_gamepad_data() and that function has returned EMSCRIPTEN_RESULT_SUCCESS!

Easy bug to resolve.

**Comment by 53620583** [comment]
how to resovle this bug?

**Comment by ufna** [comment]
@53620583 fixed now :)
