### ISSUE TITLE
ATHelper: Packaging (HTML5):     SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by hamkoo** [ufna/UE-HTML5#35]
There is an error while package project to HTML5：

![image](https://user-images.githubusercontent.com/321692/162350603-e55d7319-75fc-4438-a113-80f34306db43.png)

UATHelper: Packaging (HTML5):   XXX: -o D:\resource\UE\src\UnrealEngine-4.27-html5_dev\Engine\Binaries\HTML5\UE4Game.js
UATHelper: Packaging (HTML5):   Writing manifest to D:\resource\UE\src\UnrealEngine-4.27-html5_dev\Engine\Intermediate\Build\Manifest.xml
UATHelper: Packaging (HTML5):   Building UE4Game...
UATHelper: Packaging (HTML5):   Building 2 actions with 16 processes...
UATHelper: Packaging (HTML5):     [1/2] UE4Game.js
UATHelper: Packaging (HTML5):     Traceback (most recent call last):
UATHelper: Packaging (HTML5):       File "D:\resource\UE\src\UnrealEngine-4.27-html5_dev\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.0.0\upstream\emscripten\emcc.py", line 41, in <module>
UATHelper: Packaging (HTML5):         import emscripten
UATHelper: Packaging (HTML5):       File "D:\resource\UE\src\UnrealEngine-4.27-html5_dev\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.0.0\upstream\emscripten\emscripten.py", line 25, in <module>
UATHelper: Packaging (HTML5):         from tools import shared
UATHelper: Packaging (HTML5):       File "D:\resource\UE\src\UnrealEngine-4.27-html5_dev\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.0.0\upstream\emscripten\tools\shared.py", line 1327, in <module>
UATHelper: Packaging (HTML5):         verify_settings()
UATHelper: Packaging (HTML5):       File "D:\resource\UE\src\UnrealEngine-4.27-html5_dev\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.0.0\upstream\emscripten\tools\shared.py", line 1299, in verify_settings
UATHelper: Packaging (HTML5):         if Settings.ASM_JS not in [1, 2]:
UATHelper: Packaging (HTML5):       File "D:\resource\UE\src\UnrealEngine-4.27-html5_dev\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.0.0\upstream\emscripten\tools\shared.py", line 1286, in __getattr__
UATHelper: Packaging (HTML5):         return getattr(self.instance(), attr)
UATHelper: Packaging (HTML5):       File "D:\resource\UE\src\UnrealEngine-4.27-html5_dev\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.0.0\upstream\emscripten\tools\shared.py", line 1282, in instance
UATHelper: Packaging (HTML5):         SettingsManager.__instance = SettingsManager.__impl()
UATHelper: Packaging (HTML5):       File "D:\resource\UE\src\UnrealEngine-4.27-html5_dev\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.0.0\upstream\emscripten\tools\shared.py", line 1152, in __init__
UATHelper: Packaging (HTML5):         self.reset()
UATHelper: Packaging (HTML5):       File "D:\resource\UE\src\UnrealEngine-4.27-html5_dev\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.0.0\upstream\emscripten\tools\shared.py", line 1161, in reset
UATHelper: Packaging (HTML5):         exec(settings, {'attrs': cls.attrs})
UATHelper: Packaging (HTML5):       File "<string>", line 1637
UATHelper: Packaging (HTML5):         /*
UATHelper: Packaging (HTML5):         ^
UATHelper: Packaging (HTML5):     SyntaxError: invalid syntax
UATHelper: Packaging (HTML5): Took 10.2518181s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (HTML5): UnrealBuildTool failed. See log for more details. (D:\resource\UE\src\UnrealEngine-4.27-html5_dev\Engine\Programs\AutomationTool\Saved\Logs\UBT-UE4Game-HTML5-Development.txt)
PackagingResults: Error: invalid syntax
UATHelper: Packaging (HTML5): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (HTML5): BUILD FAILED
PackagingResults: Error: Unknown Error

**Comment by ufna** [comment]
UE 4.27 is not supported (and won't be in nearest time), dev branch is really a dev branch with unfinished state of work :)
