### ISSUE TITLE
HTML5Setup.sh problems

### ISSUE THREAD

**Issue by cheboot** [ufna/UE-HTML5#40]
/c/UEHTML5/UnrealEngine/Engine/Platforms/HTML5
Cloning into 'emsdk-3.1.4'...
remote: Enumerating objects: 3580, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 3580 (delta 3), reused 5 (delta 3), pack-reused 3569
Receiving objects: 100% (3580/3580), 2.11 MiB | 2.55 MiB/s, done.
Resolving deltas: 100% (2356/2356), done.
Python

I think problem is here: "Python"
GenerateProjectFiles.bat also have errors

$ cmake --version
cmake version 3.26.0-rc3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

$ python3 --version
Python

$ python --version
Python 3.7.9

$ ./GenerateProjectFiles.bat
Setting up Unreal Engine 4 project files...
ERROR: EMSCRIPTEN NOT FOUND: C:\UEHTML5\UnrealEngine\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.1.4\upstream\emscripten
*** EMSCRIPTEN_ROOT directory NOT FOUND: error_emscripten_not_found
ERROR: NODEJS NOT FOUND: C:\UEHTML5\UnrealEngine\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.1.4\node\14.18.2_64bit\bin\node.exe
*** NODE_JS NOT FOUND: error_nodejs_not_found
ERROR: LLVM NOT FOUND: C:\UEHTML5\UnrealEngine\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.1.4\upstream\bin
*** LLVMROOT directory NOT FOUND: error_llvm_not_found
*** PYTHON NOT FOUND: C:\UEHTML5\UnrealEngine\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.1.4\python\3.9.2_64bit\python.exe
*** EMSCRIPTEN_ROOT directory NOT FOUND: error_emscripten_not_found
*** NODE_JS NOT FOUND: error_nodejs_not_found
*** LLVMROOT directory NOT FOUND: error_llvm_not_found
*** PYTHON NOT FOUND: C:\UEHTML5\UnrealEngine\Engine\Platforms\HTML5\Build\emsdk\emsdk-3.1.4\python\3.9.2_64bit\python.exe
Binding IntelliSense data... 100%
Writing project files... 100%

**Comment by ufna** [comment]
Currently this plugin is very outdated with internal dev branch, I recommend to use https://github.com/SpeculativeCoder/UnrealEngine-HTML5-ES3
