### ISSUE TITLE
Fix emscripten crash with emscripten_set_click_callback for "fullscreen_request"

### ISSUE THREAD

**Issue by ufna** [ufna/UE-HTML5#9]

**Comment by kithe-raker** [comment]
I'm facing with this issue, really want to fix it.
But myself is a newbie to these kind of engine stuff, so do you have any suggestion?
maybe I could give you a hand :)

**Comment by ufna** [comment]
@kithe-raker , I think I'll handle this in two weeks :)

**Comment by kithe-raker** [comment]
appreciate that
